# Cloudformation script for Minerva Author cloud backend

Parameters:
  StackPrefix:
    Type: String
    Description: Unique prefix used in related stacks for use by export
  Stage:
    Type: String
    Description: Deployment stage
  ProjectTag:
    Type: String
    Description: Project tag

Resources:
  StoryBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: project
          Value: !Ref ProjectTag
    DeletionPolicy: Retain

  MinervaStoryBaseBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: project
          Value: !Ref ProjectTag

  PublishedBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: project
          Value: !Ref ProjectTag
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: PublishedBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref PublishedBucket
                - /*
      Bucket: !Ref PublishedBucket

  S3BucketTileARN:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${StackPrefix}/${Stage}/author/S3BucketStoryARN
      Description: S3 Bucket ARN for Minerva Author story data
      Type: String
      Value: !GetAtt StoryBucket.Arn

  S3PublishedBucketTileARN:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${StackPrefix}/${Stage}/author/S3BucketPublishedARN
      Description: S3 Bucket ARN for static published Minerva Story images and other content
      Type: String
      Value: !GetAtt PublishedBucket.Arn

  S3MinervaStoryBaseBucketARN:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${StackPrefix}/${Stage}/author/S3MinervaStoryBaseBucketARN
      Description: S3 Bucket ARN for minerva-story base
      Type: String
      Value: !GetAtt MinervaStoryBaseBucket.Arn

  URLPublishedStoryARN:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${StackPrefix}/${Stage}/author/URLPublishedStoryARN
      Description: URL for the published stories
      Type: String
      Value: !GetAtt
        - PublishedBucket
        - WebsiteURL

  MinervaBrowserURL:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${StackPrefix}/${Stage}/author/MinervaBrowserURL
      Description: URL for the minerva-browser library
      Type: String
      Value: "https://cdn.jsdelivr.net/npm/minerva-browser@2.10.0/build/bundle.js"
