service: ${file(${opt:config}):StackPrefix}-${file(${opt:config}):Stage}-serverless-batch

provider:
  name: aws
  region: ${file(${opt:config}):Region}
  stage: ${file(${opt:config}):Stage}
  runtime: python3.6
  vpc:
    securityGroupIds:
      - ${ssm:/${self:provider.environment.STACK_PREFIX}/${self:provider.environment.STAGE}/common/GeneralSGID}
      # Default SG for SSM
      - ${file(${opt:config}):DefaultSecurityGroup}
    # Private subnets with internet routing
    subnetIds: ${file(${opt:config}):SubnetsPrivate}
  deploymentBucket:
    name: ${file(${opt:config}):DeploymentBucket}
  environment:
    # TODO Inject these from minerva-configs
    STACK_PREFIX: ${file(${opt:config}):StackPrefix}
    STAGE: ${file(${opt:config}):Stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - batch:DescribeJobs
        - batch:SubmitJob
      # TODO Restrict to SSM provided resources (if even possible?)
      Resource: "*"
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
      Resource: "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/${self:provider.environment.STACK_PREFIX}/${self:provider.environment.STAGE}/*"
    - Effect: Allow
      Action: states:StartExecution
      Resource: "arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:stateMachine:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-ScanSM"
    - Effect: Allow
      Action: s3:ListBucket
      Resource: "${ssm:/${self:provider.environment.STACK_PREFIX}/${self:provider.environment.STAGE}/common/S3BucketRawARN}"
    - Effect: Allow
      Action:
        - s3:PutObjectTagging
        - s3:DeleteObject
      Resource: "${ssm:/${self:provider.environment.STACK_PREFIX}/${self:provider.environment.STAGE}/common/S3BucketRawARN}/*"

functions:
  addS3ManifestKeysToImport:
    name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-addS3ManifestKeysToImport
    handler: s3_sync.addS3ManifestKeysToImport

  submitSyncJob:
    name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-submitSyncJob
    handler: s3_sync.submit_job

  checkStatusSyncJob:
    name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-checkStatusSyncJob
    handler: s3_sync.check_status_job

  startScanSFN:
    name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-startScanSFN
    handler: s3_sync.start_scan_sfn

  submitScanJob:
    name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-submitScanJob
    handler: bf_scan.submit_job

  checkStatusScanJob:
    name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-checkStatusScanJob
    handler: bf_scan.check_status_job

  registerFileset:
    name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-registerFileset
    handler: bf_extract.register_fileset

  submitExtractJob:
    name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-submitExtractJob
    handler: bf_extract.submit_job

  checkStatusExtractJob:
    name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-checkStatusExtractJob
    handler: bf_extract.check_status_job

  handleRawStorageLevel:
    name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-handleRawStorageLevel
    handler: bf_extract.handle_raw_storage_level

stepFunctions:
  stateMachines:
    S3EFSSyncSM:
      name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-S3EFSSyncSM
      definition:
        Comment: Complete workflow of syncing data from S3 to EFS
        StartAt: RegisterImportManifest
        States:
          RegisterImportManifest:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-addS3ManifestKeysToImport
            ResultPath: null
            Next: SubmitJob
          SubmitJob:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-submitSyncJob
            ResultPath: $.jobId
            Next: Wait30
          Wait30:
            Type: Wait
            Seconds: 30
            Next: GetJobStatus
          GetJobStatus:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-checkStatusSyncJob
            InputPath: $.jobId
            ResultPath: $.status
            Next: IsJobComplete
          IsJobComplete:
            Type: Choice
            Choices:
              - Variable: $.status
                StringEquals: FAILED
                Next: JobFailed
              - Variable: $.status
                StringEquals: SUCCEEDED
                Next: GetFinalJobStatus
            Default: Wait30
          JobFailed:
            Type: Fail
            Cause: S3 Sync Batch Job Failed
            Error: DescribeJob returned FAILED
          GetFinalJobStatus:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-checkStatusSyncJob
            InputPath: $.jobId
            ResultPath: $.status
            Next: StartScanSFN
          StartScanSFN:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-startScanSFN
            InputPath: $.import_uuid
            ResultPath: $.scanArn
            End: true

    ScanSM:
      name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-ScanSM
      definition:
        Comment: Complete worlflow of scanning data in EFS for filesets
        StartAt: SubmitJob
        States:
          SubmitJob:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-submitScanJob
            ResultPath: $.jobId
            Next: Wait30
          Wait30:
            Type: Wait
            Seconds: 30
            Next: GetJobStatus
          GetJobStatus:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-checkStatusScanJob
            InputPath: $.jobId
            ResultPath: $.status
            Next: IsJobComplete
          IsJobComplete:
            Type: Choice
            Choices:
              - Variable: $.status
                StringEquals: FAILED
                Next: JobFailed
              - Variable: $.status
                StringEquals: SUCCEEDED
                Next: GetFinalJobStatus
            Default: Wait30
          JobFailed:
            Type: Fail
            Cause: Bioformats Scan Job Failed
            Error: DescribeJob returned FAILED
          GetFinalJobStatus:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-checkStatusScanJob
            InputPath: $.jobId
            End: true

    ExtractSM:
      name: ${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-ExtractSM
      definition:
        Comment: Complete workflow of extracting Filesets in EFS into metadata and pyramid tiles
        StartAt: RegisterFileset
        States:
          RegisterFileset:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-registerFileset
            ResultPath: $.fileset_uuid
            Next: SubmitJob
          SubmitJob:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-submitExtractJob
            ResultPath: $.jobId
            Next: Wait30
          Wait30:
            Type: Wait
            Seconds: 30
            Next: GetJobStatus
          GetJobStatus:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-checkStatusExtractJob
            InputPath: $.jobId
            ResultPath: $.status
            Next: IsJobComplete
          IsJobComplete:
            Type: Choice
            Choices:
              - Variable: $.status
                StringEquals: FAILED
                Next: JobFailed
              - Variable: $.status
                StringEquals: SUCCEEDED
                Next: HandleRawStorageLevel
            Default: Wait30
          JobFailed:
            Type: Fail
            Cause: Bioformats Extract Job Failed
            Error: DescribeJob returned FAILED
          HandleRawStorageLevel:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-handleRawStorageLevel
            ResultPath: null
            Next: GetFinalJobStatus
          GetFinalJobStatus:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:provider.environment.STACK_PREFIX}-${self:provider.environment.STAGE}-checkStatusExtractJob
            InputPath: $.jobId
            End: true

# TODO Revert to using stock serverless-step-functions (see package.json) if the
# issue regarding key name referencing can be resolved (potentially with my PR):
# https://github.com/horike37/serverless-step-functions/pull/143

resources:
  Resources:

    S3EFSSyncStepARN:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /${self:provider.environment.STACK_PREFIX}/${self:provider.environment.STAGE}/batch/S3EFSSyncStepARN
        Description: ARN of step function for S3 EFS Sync
        Type: String
        Value:
          Ref: S3EFSSyncSMStepFunctionsStateMachine

    ScanStepARN:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /${self:provider.environment.STACK_PREFIX}/${self:provider.environment.STAGE}/batch/ScanStepARN
        Description: ARN of step function for scan
        Type: String
        Value:
          Ref: ScanSMStepFunctionsStateMachine

    ExtractStepARN:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /${self:provider.environment.STACK_PREFIX}/${self:provider.environment.STAGE}/batch/ExtractStepARN
        Description: ARN of step function for extract
        Type: String
        Value:
          Ref: ExtractSMStepFunctionsStateMachine

  #
  # Outputs:
  #   writeEvent:
  #     Value:
  #       Ref: WriteEventLambdaFunction
  #     Export:
  #       Name: ${self:service}-${opt:stage}-LambdaWriteEvent


plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-step-functions
custom:
  pythonRequirements:
    dockerizePip: non-linux
